NOW-859 - Publish the rum npm package to the public npm registry
OpsVerseIO/real-user-monitoring pull request #1
Opened 2022-05-26 07:13 UTC by chethan-devopsnow

2022-05-26 14:11 UTC, vinaya-devopsnow commented on README.md
> +Opsverse Browser RUM uses OpenTelemetry standards to enable High-quality, ubiquitous, and portable telemetry to enable effective observability. Opsverse RUM pacakge can be used to instrument, generat
packages -- pacakge

2022-05-26 14:11 UTC, vinaya-devopsnow commented on README.md
> +### For Javascript frameworks
what does javascript framework mean ? html and javascript based application ? 
vanilla javascript , right ?

2022-05-26 14:11 UTC, vinaya-devopsnow commented on README.md
> +### For Javascript frameworks
where would we get end point url

2022-05-26 14:11 UTC, vinaya-devopsnow commented on README.md
> +        serviceName: ” “,//For trackign purpose
tracking from trackign

2022-05-26 14:11 UTC, vinaya-devopsnow commented on README.md
> +Opsverse Browser RUM uses OpenTelemetry standards to enable High-quality, ubiquitous, and portable telemetry to enable effective observability. Opsverse RUM pacakge can be used to instrument, generat
OpsVerse from Opsverse

2022-05-26 14:11 UTC, vinaya-devopsnow commented on src/index.js
> +  let authKey = "ZGV2b3Bzbm93OndlaXJkaGVhdDE4";
where is this key used ?

2022-05-26 14:11 UTC, vinaya-devopsnow commented on src/index.js
> +    "https://jaeger-collector-pearjet.observe.devopsnow.cloud/api/v2/spans";
what is this hard coding ?

2022-05-30 20:30 UTC, navinpai commented on README.md
> +        serviceName: ” “,//For trackign purpose
Typo: trackign

2022-05-30 20:30 UTC, navinpai commented on README.md
> +@opentelemetry/sdk-trace-web @opentelemetry/instrumentation-document-load @opentelemetry/context-zone @opentelemetry/instrumentation @opentelemetry/instrumentation-fetch @opentelemetry/propagator-b3
Add links?

eg. [@opentelemetry/sdk-trace-web](https://www.npmjs.com/package/@opentelemetry/sdk-trace-web)

2022-05-30 20:30 UTC, navinpai commented on index.js.LICENSE.txt
> + * @license
Is this license correct?

2022-05-30 20:30 UTC, navinpai commented on webpack.config.js
> +    library: "my-library",
Nit: Change lib name to `OpsVerseRum` ?

2022-05-31 07:14 UTC, sat-devopsnow requested changes

2022-05-31 07:14 UTC, sat-devopsnow commented on README.md
> +        authKey: ” “, //Pass the authentication key
What is `authKey` used for? And where do we get it from?

I know this is the basic auth (base54 encoded), but users will see this and probably stop there with any instrumentation, so please add this bit to `README` too - so they know when/where to get it.

It's good to put dummy (life-like) values in examples (instead of blank) to help guide users with instrumentation.l

2022-05-31 07:14 UTC, sat-devopsnow commented on src/index.js
> +        sampler: new TraceIdRatioBasedSampler(1),
Do you want to also pass the sampler ratio as a param? It can default to `1` if none is provided.

2022-05-31 07:14 UTC, sat-devopsnow commented on src/index.js
> +            propagateTraceHeaderCorsUrls: [/http:\/\/localhost:*\.*/],
Should this be hardcoded to localhost, or should this capture everything? .. e.g., `/.+/g` ?

2022-05-31 08:35 UTC, chethan-devopsnow commented on README.md
> +Opsverse Browser RUM uses OpenTelemetry standards to enable High-quality, ubiquitous, and portable telemetry to enable effective observability. Opsverse RUM pacakge can be used to instrument, generat
done

2022-06-02 07:54 UTC, vinaya-devopsnow approved these changes

2022-06-02 16:41 UTC, sat-devopsnow requested changes

2022-06-02 16:41 UTC, sat-devopsnow commented on index.js.LICENSE.txt
> + * @license
Any background on why this was closed? This is the license we want?

2022-06-02 16:41 UTC, sat-devopsnow commented on src/index.js
> +            ignoreUrls: [/localhost:8090\/sockjs-node/],
Provide comment(s) on:

- why we picked localhsot:8090 to ignore it
- why is httpbin.org added to the propogateTraceHearderCorsUrls (would the first regex simply catch that?)

2022-06-02 16:41 UTC, sat-devopsnow commented on README.md
> +OpsVerse Browser RUM uses OpenTelemetry standards to enable high quality, ubiquitous, and portable telemetry to enable effective observability. OpsVerse browser rum package can be used to instrument,
Change `OpsVerse browser rum package` to `OpsVerse browser RUM package`

2022-06-02 16:41 UTC, sat-devopsnow commented on README.md
> +### Real User Monitoring (Browser Implementation)
In Markdown, typically begin with H1 (e.g., `#`)... think of them as logically nested sections...

So please format this as something like:

```
# Real User Monitoring

## Browser Instrumentation

### Overview

### Setup 

#### For HTML and Javascript based application

#### For NextJS

## NodeJS Instrumentation

### Overview

### Setup
```

This should also allow you to remove the `=========` which seem to overrun in my browser.

2022-06-02 16:41 UTC, sat-devopsnow commented on README.md
> +You are now good to use the [OpsVerse](https://opsverse.io) monitoring tool now!
Perhaps move the `Start Your Application` section here and add this line to that section?

So something like:

```
## Start your application

Now, build your application and run your code in the browser. In the console/network tab of the browser's developer toolbar you should see some traces being exported to the collector URL.

See [OpsVerse support docs](https://docs.opsverse.io) for reference.
```

:point_up: Change the docs link to the exact docs page that talks about RUM.

Also change:

```
You are now good to use the [OpsVerse](https://opsverse.io) monitoring tool now!
```

to something like:

```
You are now good to send traces to any OpenTelemetry Collector. This library was specifically crafted so that you may additionally get Real User Monitoring metrics if by sending to the OpenTelemetry Collector you launched via [Opsverse](https://console.opsverse.io)
```

2022-06-02 16:41 UTC, sat-devopsnow commented on README.md
> +        OpsVerseRum.start({
Perhaps change from:

```
            authKey: "<base64 encoded>",
            serviceName: "<unique tracing id>",
            collectorUrl: "<OpsVerse collector url>",
```

to

```
            authKey: "<B64EncodedBasicAuthToCollectorUrl>",
            serviceName: "example-service",
            collectorUrl: "<OpenTelemetryCollectorUrl>",
```

Add a section where they can get the collector URL and auth key if they don't have one already (this may not be obvious to new users looking at this library)... e.g., "you may launch an open standards observability stack on [OpsVerse](https://console.opsverse.io)"

2022-06-10 10:01 UTC, vinaya-devopsnow approved these changes

2022-06-10 10:51 UTC, merged